### ISSUE TITLE
Document process for contributing

### ISSUE THREAD

**Issue by TheLonelyGhost** [TranscribersOfReddit/TranscribersOfReddit#14]
Many repositories have instructions for new contributors in `CONTRIBUTING.md` or as part of `README.md`. It might be good to revise the current documentation with topics such as:

- [ ] Setting up local dev environment (virtualenv, service stubbing to block calls to reddit)
- [x] Testing changes (automated tests? linting?)
- [x] Forking and submitting a pull request on Github
- [x] What does the development process look like for a feature? for a bug?
- [ ] When can a contributor expect their changes to be pushed live?

**Comment by itsthejoker** [comment]
Actually, let's split this into a few different tickets. Setting up a repeatable, clean dev environment should definitely be its own ticket -- possibly rolled in with testing? We already have tickets for implementing unit tests for both bots, even though most of the code is only used by u/ToR. Dedicated information for forking and all that should probably be its own ticket too; what do you think?

**Comment by TheLonelyGhost** [comment]
That was my intention. I'm currently writing up the ticket for setting up the dev environment, this is just a wrap up for documenting it.

That said, it could also be treated like a planning-phase task to figure out how we want to do each of these tasks.

Either way, the scope is just the documentation part of it, not changing any code.

**Comment by itsthejoker** [comment]
Ah, I misunderstood. Carry on. :)

**Comment by TheLonelyGhost** [comment]
I feel like most of this is complete, at least to the point where the ticket title and description don't really fit the remaining work. Will open separate tickets for individual tasks remaining and link them here.

**Comment by TheLonelyGhost** [comment]
Tickets have been split up. Closing...
