### ISSUE TITLE
Come up with new subs to approach

### ISSUE THREAD

**Issue by Kumalumajuma** [TranscribersOfReddit/TranscribersOfReddit#22]

**Comment by captcoe** [comment]
/r/Tinder

**Comment by Kumalumajuma** [comment]
https://docs.google.com/spreadsheets/d/12Hwzj8u71N1xDJehInlC3R7AIWj6mv3CSm2Z-oSNHSM/edit?usp=sharing

Spreadsheet of all ideas with progress details on each. Please read/update as necessary

**Comment by TheLonelyGhost** [comment]
Seems like this discussion now lives in the above linked spreadsheet. Closing...
