### ISSUE TITLE
[RFC] Remove unclaimed posts older than 18 hours

### ISSUE THREAD

**Issue by TheLonelyGhost** [TranscribersOfReddit/TranscribersOfReddit#26]
Add a bot to delete posts older than a certain age (e.g., 18 hours).

Per a discussion from the mods, this likely needs to be fleshed out more. Thoughts are welcome in the comments.

**Comment by itsthejoker** [comment]
The work that the volunteers put in is only valuable during a short window after a post is made. Ideally, we want to have a transcription on a post within an hour after it's posted. After an hour has passed, it's still useful, but fewer people will see it; after a longer set of time (the amount we've been working under has been 18 hours) we assume that a post has lost all momentum and is not worth the time to transcribe it any longer.

Therefore, it would make sense to have an automated system to perform this culling of unclaimed posts once they reach an expiry time. This is not a high priority bot; it could also run on a period, something like 10-15 minutes of waiting between each run.

**Comment by itsthejoker** [comment]
This was completed by @arfie with the addition of u/ToR_archivist.

**Comment by itsthejoker** [comment]
See #35
