### ISSUE TITLE
Allow handling of deleted comments

### ISSUE THREAD

**Issue by itsthejoker** [TranscribersOfReddit/TranscribersOfReddit#29]
u/ToR has an edge case where someone will make a comment, the bot will grab the inbox, and the user will delete the comment between the time when the comment is grabbed from the inbox and when it is processed. This crashes the bot; see https://app.bugsnag.com/transcribersofreddit/u-slash-tor/errors/593b5b0ab4782d001873a7dd?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open for full error example.

1) identify everywhere the bot can be halted by a deleted comment
2) implement way to protect against a deleted comment exception

**Comment by TheLonelyGhost** [comment]
Closed by #57
