### ISSUE TITLE
Tests for Apprentice Bot

### ISSUE THREAD

**Issue by itsthejoker** [TranscribersOfReddit/TranscribersOfReddit#3]
Currently the bot has no unittests. This needs to change, preferably with pytest and Travis CI integration.

**Comment by TheLonelyGhost** [comment]
With unit tests we need to make sure we're stubbing out calls to the real Reddit API.

I'm not picky on the particular methods: stubs, mocks, implementing an adapter interface and swapping it out during testing. I'd just argue the developer shouldn't need to go too far out of their way to make sure they're not leaking a testing state to the outside world.

**Comment by itsthejoker** [comment]
Definitely. Something my work does that I really like is adding a special "settings_local" file in that overwrites specific keys to make everything local-only.  It's already set in .gitignore, so the base settings_local is just something we can copy / paste from a wiki page and the bot functions normally without it. That's kind of what I'm hoping we can integrate here.

**Comment by TheLonelyGhost** [comment]
Moved to TranscribersOfReddit/ToR_OCR#5
