### ISSUE TITLE
Document hosting dependencies

### ISSUE THREAD

**Issue by TheLonelyGhost** [TranscribersOfReddit/TranscribersOfReddit#37]
Document steps to setup ToR bots, which can be later translated to cloud hosting. This might be best placed in the Github repository wiki.

- [x] What is the assumed operating system? (if Linux, what distribution and version?)
- [x] What native packages are required to be installed? (might be covered by `bin/run setup`, but needs confirmation)
- [x] What external services (e.g., Redis, a subreddit) are assumed to exist?
- [x] What schema does Redis use for its data structures?
- [x] How might one create new or retrieve existing auth credentials for bots to go in `praw.ini`?

... probably more.

(Split from #14)

**Comment by TheLonelyGhost** [comment]
Assigning @itsthejoker since he has the most knowledge on how hosting is currently done.

**Comment by itsthejoker** [comment]
How does this look? https://github.com/TranscribersOfReddit/TranscribersOfReddit/wiki/Hosting-Requirements

**Comment by TheLonelyGhost** [comment]
There are multiple mentions of using an old version of ubuntu. For the purposes of upgrade planning, what version of tesseract is required for python integration?

**Comment by itsthejoker** [comment]
3.04 is required for the python library, but the ubuntu package is 3.02.
