### ISSUE TITLE
Trial header/footer for Transcribot comments

### ISSUE THREAD

**Issue by astheriae** [TranscribersOfReddit/TranscribersOfReddit#48]

**Comment by astheriae** [comment]
Had the idea to add the basic formatting to Transcribot's comments to save extra copy/pasting.  Could consist of 'Image Transcription: <Type of Image>' at the top and the 'I'm a volunteer...etc.' text at the bottom 

Would have to investigate what would happen with comments over 9000 characters

**Comment by TheLonelyGhost** [comment]
Perhaps we would have to include pagination past a certain number of characters. Should it be another comment on the same level or having this new comment be the parent of the next page?

**Comment by astheriae** [comment]
I'm not sure that I understand what you mean, but if I do then I meant as part of the same comment 

so transcibot's comment would be like

Image Transcription: <Type of image>

---

Blah blah blah, 
she said
he said 
etc.

---

footnote text

---

This message has been posted by a bot...

**Comment by itsthejoker** [comment]
@TheLonelyGhost we'd probably stick with the parent structure like we're already doing -- every 9000 characters it gets broken off and the next chunk is added as a reply to the previous chunk. I'm thinking we keep track of which chunk is the last chunk and add the footer there.

@astheriae he means how to break apart the chunks and how they'll be displayed in the reddit thread -- also where to put the actual footer and such.

**Comment by itsthejoker** [comment]
@TheLonelyGhost 

https://github.com/TranscribersOfReddit/ToR_OCR/blob/master/tor_ocr/main.py#L69-L76
https://github.com/TranscribersOfReddit/ToR_OCR/blob/master/tor_ocr/main.py#L140-L144

**Comment by astheriae** [comment]
Ohhh I get you now! Yeah I agree that it should remain as a child comment and then the last one would have the footer.

Otherwise it'd be a bit annoying if they all had it on, and if it was in the first comment readers would likely forget about it by the time they got to the end and then be less likely to find out more about us :)

**Comment by TheLonelyGhost** [comment]
Moved to TranscribersOfReddit/ToR_OCR#7
