### ISSUE TITLE
Wiki Stub caching in Redis

### ISSUE THREAD

**Issue by itsthejoker** [TranscribersOfReddit/TranscribersOfReddit#5]
Right now, the bot requests each wiki stub as it's needed. This is very inefficient.

**Acceptance Criteria:**
1) No stubs are downloaded on initialization
2) When a stub is requested, it's downloaded and stored in Redis
3) On a reload, the caches are cleared

**Comment by TheLonelyGhost** [comment]
Moved to TranscribersOfReddit/tor_core#9
