### ISSUE TITLE
Add Hacktoberfest label to issues for visibility

### ISSUE THREAD

**Issue by TheLonelyGhost** [TranscribersOfReddit/TranscribersOfReddit#50]
Digital Ocean does a Hacktoberfest every October and monitors for number of pull requests a user opens during that time. We can use that to help clean up and refactor the project.

Here are a few examples: https://github.com/search?l=&q=state:open+label:hacktoberfest&ref=advsearch&type=Issues&utf8=✓

Hacktoberfest homepage: https://hacktoberfest.digitalocean.com

**Comment by itsthejoker** [comment]
Done!
