### ISSUE TITLE
Improve OCR accuracy

### ISSUE THREAD

**Issue by itsthejoker** [TranscribersOfReddit/TranscribersOfReddit#7]
u/transcribot currently has a lot of issues with posts as they come from imgur and i.redd.it. Investigate enlarging pictures by 125% or greater and see if this increases OCR success rates.

**Comment by nekoworkshop** [comment]
Hi Joe. I ran into a volunteer transcriber on Reddit and has been wondering if there is a bot that can do that automatically. Glad to see the work already being done :)

A stupid question if you don't mind. I would like to contribute to improving the OCR of transcribot and I'm aware that the bot should be using Tesseract. However, I'm not seeing it in the code anywhere. 

Is that part of the code not uploaded or am I missing something here?

**Comment by itsthejoker** [comment]
Hi, @nekoworkshop! You're not missing anything and your eyes do not deceive you! When this issue was made, the OCR was being performed this repo; we've since split all the bots into their own repos :) You can find the OCR side over here: https://github.com/TranscribersOfReddit/ToR_OCR

**Comment by itsthejoker** [comment]
@nekoworkshop Also, since I forgot to mention it earlier, we've been working on (but don't yet) have a testing framework. Essentially our current system is "build what should work and what you can test on your own, then integrate it and make a PR and we'll fix what we need to". It's horrifying and awful, but working primarily with Reddit makes creating a comprehensive test suite difficult.

**Comment by TheLonelyGhost** [comment]
Moved to TranscribersOfReddit/ToR_OCR#3
