### ISSUE TITLE
Flag NSFW posts as NSFW

### ISSUE THREAD

**Issue by perryprog** [TranscribersOfReddit/TranscribersOfReddit#71]
Crazy idea right

Specifically: if a post that the bot pulls is marked NSFW, make the new post on r/ToR NSFW as well.

**Comment by itsthejoker** [comment]
This is already automatically performed as a function of Reddit. There is nothing we can do if a moderator marks the post as NSFW on the sub after it's been crossposted.

**Comment by perryprog** [comment]
Sorry, I mean something like when someone posts a NSFW (or posts on a NSFW sub) post, and tags it as such. (not sure if you can mark posts as NSFW _when_ you post it)

For example, someone posts on some NSFW sub in general, then u/ToR posts it as such. It also wouldn't be a bad idea to see if by the time it's in the inbox if it's been tagged NSFW. 

Also,
> Might need to talk to Joker about getting all of those posts autoflagged NSFW, then
— Captcoe

**Comment by TheLonelyGhost** [comment]
Ah, so you're saying something like if we (for some reason) transcribed content from /r/gonewild, for example, we would mark the transcription request in /r/tor as NSFW.

The topic of NSFW content in /r/tor came up in the mod slack and I believe we decided it's not worth the legal risk (minors viewing adult content, etc.) to even take on NSFW transcriptions. That said, I'm not sure we've defined where that line of NSFW content is quite yet (e.g., is /r/4chan a NSFW sub?).

Regardless of where we decide the line is, flagging NSFW content will not be an issue we would need to tackle.

**Comment by perryprog** [comment]
<img width="272" alt="screen shot 2017-11-12 at 6 43 42 pm" src="https://user-images.githubusercontent.com/12972285/32704805-6e0dfd88-c7d9-11e7-898d-0c9fc922a927.png">
^^ r/4chan sidebar

I mean, even the cursor in r/4chan is a penis now. Also, to be clear this came up in a discord conversation with CaptCoe and some other dude, I just forwarded it here.
